### PR TITLE
Add instructions for configuration and ingesting

### PR DESCRIPTION
**Pull request by bondjimbond**
Updates the README to help users understand the module required objects (i.e. jstree 3.0.0) and ingest process.

### CODE REVIEW

**Comment by bryjbrown** [comment]
@bondjimbond Did you mean to PR this repo? The FLVC fork is really only for FL-Islandora development, https://github.com/discoverygarden/islandora_solution_pack_serial is the upstream community fork.

Also, it appears that you made the same PR twice:
- https://github.com/FLVC/islandora_solution_pack_serial/pull/1
- https://github.com/FLVC/islandora_solution_pack_serial/pull/2

**Comment by bondjimbond** [comment]
Yeah, the second one was for the FLVC branch, after I realized/remembered that the 7.x branch isn't where you've got the latest changes. You can close #1 in favour of #2.

**Comment by bryjbrown** [comment]
@bondjimbond So why PR the https://github.com/FLVC/islandora_solution_pack_serial instead of https://github.com/discoverygarden/islandora_solution_pack_serial? We have some stuff in https://github.com/FLVC/islandora_solution_pack_serial customized for FL-Islandora that you may not want on your instance?

**Comment by bondjimbond** [comment]
Last we talked about this SP, you suggested using the flvc branch... I can't remember what changes you've made, but I think they're all improvements over the original. I've also PR'd the original -- it's nice to have better documentation all round.

**Pull request closed without merging**
